import os

# TELEGRAM VARIABLES
TELEGRAM_TOKEN = os.environ.get('TELEGRAM_TOKEN')

# SERVICE PROVIDERS VARIABLES
SOURCE_DOMAIN = os.environ.get('SOURCE_DOMAIN')
PLAYER_DOMAIN = os.environ.get('PLAYER_DOMAIN')

# USERS VARIABLES
ADMIN_USERNAME = os.environ.get('ADMIN_USERNAME')
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')
USER_PASSWORD = os.environ.get('USER_PASSWORD')
USER_EMAIL_PREFIX = os.environ.get('USER_EMAIL_PREFIX')

# EMAIL VARIABLES
GMAIL_ADMIN_ACCOUNT = os.environ.get('GMAIL_ADMIN_ACCOUNT')
GMAIL_ADMIN_PASSWORD = os.environ.get('GMAIL_ADMIN_PASSWORD')
GMAIL_SOURCE_PLAYER_ACCOUNT = os.environ.get('GMAIL_SOURCE_PLAYER_ACCOUNT')
GMAIL_SOURCE_PLAYER_PASSWORD = os.environ.get('GMAIL_SOURCE_PLAYER_PASSWORD')

# CAPTCHA VARIABLES
CAPTCHA_API_KEY = os.environ.get('CAPTCHA_API_KEY')
CAPTCHA_SITE_KEY = os.environ.get('CAPTCHA_SITE_KEY')
CAPTCHA_URL = os.environ.get('CAPTCHA_URL')
